version: "3"

services:
  local-api:
    image: aiogram/telegram-bot-api
    network_mode: host
    environment:
      TELEGRAM_API_ID: $TELEGRAM_API_ID
      TELEGRAM_API_HASH: $TELEGRAM_API_HASH
      TELEGRAM_LOCAL: 1
      TELEGRAM_STAT: 1
    restart: always
