version: "3"

services:
  telegram-bot-api:
    image: gramoss/telegram-bot-api:ade0841
    network_mode: host
    environment:
      TELEGRAM_API_ID: $TELEGRAM_API_ID
      TELEGRAM_API_HASH: $TELEGRAM_API_HASH
      TELEGRAM_LOCAL_MODE: true
